-- Структура форума под World RP: разделы организаций (устав, заявления, жалобы на сотрудников),
-- законодательная база, восстановление имущества, новые префиксы, новая анкета техподдержки.
-- Повторный запуск безопасен: INSERT IGNORE по явным id.

INSERT IGNORE INTO prefixes (id, title, color, display_order) VALUES (13, 'Принято', 'green', 13);
INSERT IGNORE INTO prefixes (id, title, color, display_order) VALUES (14, 'Передано разработчикам', 'blue', 14);
INSERT IGNORE INTO prefixes (id, title, color, display_order) VALUES (15, 'Реализовано', 'purple', 15);
INSERT IGNORE INTO prefixes (id, title, color, display_order) VALUES (16, 'Главному администратору', 'orange', 16);
INSERT IGNORE INTO prefixes (id, title, color, display_order) VALUES (17, 'Ожидание доказательств', 'dark', 17);
INSERT IGNORE INTO prefixes (id, title, color, display_order) VALUES (18, 'Исправлено', 'green', 18);

INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (23, 20, 'forum', 'Восстановление имущества', 'Пропал дом, гараж, машина или деньги из-за ошибки сервера', 'refresh', 3, 0, 10, 10, 0, 0, 0, 1, 1, 'Восстановление имущества | Nick_Name | Что пропало', NULL, '{"title": "Восстановление имущества | {nick} | {what}", "fields": [{"key": "nick", "label": "Ваш игровой ник", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "what", "label": "Что пропало", "type": "select", "required": true, "options": ["Дом", "Гараж", "Личный транспорт", "Деньги", "Предметы инвентаря", "Другое"]}, {"key": "details", "label": "Что именно пропало и при каких обстоятельствах", "type": "textarea", "required": true, "hint": "Номер дома или гаража, модель машины, сумма. Что вы делали в момент пропажи."}, {"key": "date", "label": "Дата пропажи", "type": "date", "required": true}, {"key": "time", "label": "Примерное время (МСК)", "type": "text", "placeholder": "21:10", "max": 20}, {"key": "proof", "label": "Доказательства", "type": "url", "required": true, "hint": "Скриншоты или видео, где видно имущество до пропажи и после."}, {"key": "agree", "label": "Готов нести ответственность в случае обмана", "type": "checkbox", "text": "Да", "required": true, "hint": "Вы подтверждаете, что всё написанное - правда, и готовы понести наказание, если обман будет доказан."}]}');
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (60, 57, 'forum', 'Информация и устав Правительства', 'Устав, структура, должности и объявления мэрии', 'book', 1, 0, 20, 20, 0, 0, 0, 0, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (61, 57, 'forum', 'Заявления на трудоустройство', 'Хотите работать в мэрии - заполните заявление', 'user-plus', 2, 0, 10, 10, 0, 0, 0, 1, 1, 'Заявление на трудоустройство | Правительство | Nick_Name', NULL, '{"title": "Заявление на трудоустройство | Правительство | {nick}", "fields": [{"key": "nick", "label": "Игровой ник", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "age", "label": "Реальный возраст", "type": "number", "required": true, "max": 3}, {"key": "level", "label": "Игровой уровень", "type": "number", "required": true, "max": 4}, {"key": "post", "label": "Желаемая должность", "type": "text", "placeholder": "Например: секретарь, адвокат", "max": 60}, {"key": "about", "label": "Расскажите о себе и своём персонаже", "type": "textarea", "required": true}, {"key": "hours", "label": "Сколько часов в день готовы играть", "type": "text", "required": true, "max": 40}, {"key": "punish", "label": "Наказания за последние 30 дней", "type": "text", "required": true, "placeholder": "Нет / перечислите", "max": 200}, {"key": "discord", "label": "Discord для связи", "type": "text", "max": 64}, {"key": "agree", "label": "Готов нести ответственность в случае обмана", "type": "checkbox", "text": "Да", "required": true, "hint": "Вы подтверждаете, что всё написанное - правда, и готовы понести наказание, если обман будет доказан."}]}');
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (62, 57, 'forum', 'Жалобы на сотрудников Правительства', 'Нарушения со стороны сотрудников мэрии', 'flag', 3, 0, 10, 10, 0, 0, 0, 1, 1, 'Жалоба на сотрудника Правительства Nick_Name', NULL, '{"title": "Жалоба на сотрудника Правительства {employee}", "fields": [{"key": "nick", "label": "Ваш игровой ник", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "employee", "label": "Ник сотрудника", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "rank", "label": "Должность сотрудника, если знаете", "type": "text", "max": 60}, {"key": "essence", "label": "Суть жалобы", "type": "textarea", "required": true}, {"key": "date", "label": "Дата нарушения", "type": "date", "required": true}, {"key": "proof", "label": "Доказательства", "type": "url", "required": true, "hint": "Ссылка на видео (YouTube, VK Видео, Rutube) или скриншот."}, {"key": "agree", "label": "Готов нести ответственность в случае обмана", "type": "checkbox", "text": "Да", "required": true, "hint": "Вы подтверждаете, что всё написанное - правда, и готовы понести наказание, если обман будет доказан."}]}');
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (63, 58, 'forum', 'Информация и устав Департамента полиции', 'Устав, звания, структура и объявления департамента', 'book', 1, 0, 20, 20, 0, 0, 0, 0, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (64, 58, 'forum', 'Заявления в академию ДП', 'Набор в полицию Лос-Сантоса', 'user-plus', 2, 0, 10, 10, 0, 0, 0, 1, 1, 'Заявление в академию ДП | Nick_Name', NULL, '{"title": "Заявление в академию ДП | {nick}", "fields": [{"key": "nick", "label": "Игровой ник", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "age", "label": "Реальный возраст", "type": "number", "required": true, "max": 3}, {"key": "level", "label": "Игровой уровень", "type": "number", "required": true, "max": 4}, {"key": "about", "label": "Расскажите о себе и своём персонаже", "type": "textarea", "required": true}, {"key": "why", "label": "Почему хотите служить в полиции", "type": "textarea", "required": true}, {"key": "hours", "label": "Сколько часов в день готовы играть", "type": "text", "required": true, "max": 40}, {"key": "punish", "label": "Наказания за последние 30 дней", "type": "text", "required": true, "placeholder": "Нет / перечислите", "max": 200}, {"key": "discord", "label": "Discord для связи", "type": "text", "max": 64}, {"key": "agree", "label": "Готов нести ответственность в случае обмана", "type": "checkbox", "text": "Да", "required": true, "hint": "Вы подтверждаете, что всё написанное - правда, и готовы понести наказание, если обман будет доказан."}]}');
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (65, 58, 'forum', 'Жалобы на сотрудников ДП', 'Нарушения со стороны сотрудников полиции', 'flag', 3, 0, 10, 10, 0, 0, 0, 1, 1, 'Жалоба на сотрудника ДП Nick_Name', NULL, '{"title": "Жалоба на сотрудника ДП {employee}", "fields": [{"key": "nick", "label": "Ваш игровой ник", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "employee", "label": "Ник сотрудника", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "rank", "label": "Звание сотрудника, если знаете", "type": "text", "max": 60}, {"key": "essence", "label": "Суть жалобы", "type": "textarea", "required": true}, {"key": "date", "label": "Дата нарушения", "type": "date", "required": true}, {"key": "proof", "label": "Доказательства", "type": "url", "required": true, "hint": "Ссылка на видео (YouTube, VK Видео, Rutube) или скриншот."}, {"key": "agree", "label": "Готов нести ответственность в случае обмана", "type": "checkbox", "text": "Да", "required": true, "hint": "Вы подтверждаете, что всё написанное - правда, и готовы понести наказание, если обман будет доказан."}]}');
INSERT IGNORE INTO nodes (id, parent_id, type, title, description, icon, display_order, view_level, thread_level, reply_level, hide_if_no_access, is_closed, quick_nav, require_prefix, default_prefix_id, title_hint, thread_template, form_json) VALUES (66, 56, 'forum', 'Законодательная база штата', 'Конституция, кодексы и указы штата. Публикуют руководство Правительства и администрация', 'rules', 3, 0, 20, 80, 0, 0, 0, 0, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (52, 17);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (53, 16);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (53, 17);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (54, 17);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (55, 16);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (21, 14);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (22, 14);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (22, 18);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (40, 13);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (40, 14);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (40, 15);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (41, 13);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (41, 14);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (41, 15);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (23, 1);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (23, 2);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (23, 3);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (23, 4);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (23, 17);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (61, 1);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (61, 2);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (61, 3);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (61, 4);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (64, 1);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (64, 2);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (64, 3);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (64, 4);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (62, 1);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (62, 2);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (62, 3);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (62, 4);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (62, 17);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (65, 1);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (65, 2);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (65, 3);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (65, 4);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (65, 17);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (60, 7);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (60, 8);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (63, 7);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (63, 8);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (66, 7);
INSERT IGNORE INTO node_prefixes (node_id, prefix_id) VALUES (66, 8);

-- Анкета техподдержки: способ входа (лаунчер / клиент) и тип проблемы
UPDATE nodes SET form_json = '{"title": "{kind} | {problem}", "fields": [{"key": "nick", "label": "Ваш игровой ник", "type": "text", "required": true, "placeholder": "Имя_Фамилия", "max": 32}, {"key": "kind", "label": "Что случилось", "type": "select", "required": true, "options": ["Не запускается лаунчер", "Не скачиваются файлы игры", "Игра вылетает", "Не могу войти в аккаунт", "Ошибка в игре", "Другое"]}, {"key": "how", "label": "Как вы заходите в игру", "type": "radio", "required": true, "options": ["Через лаунчер World RP", "Клиентом SA-MP напрямую"]}, {"key": "problem", "label": "Кратко о проблеме", "type": "text", "required": true, "placeholder": "Например: вылет при входе на сервер", "max": 100}, {"key": "essence", "label": "Подробное описание", "type": "textarea", "required": true, "hint": "Когда началось, что именно происходит, текст ошибки, если есть."}, {"key": "system", "label": "Компьютер", "type": "text", "placeholder": "Windows 10, 8 ГБ памяти, видеокарта GTX 1050", "max": 150}, {"key": "tried", "label": "Что уже пробовали сделать", "type": "textarea"}, {"key": "proof", "label": "Скриншот или видео ошибки", "type": "url", "hint": "Загрузите скриншот на imgur.com или yapx.ru и вставьте ссылку."}]}', title_hint = 'Тип проблемы | Кратко о проблеме' WHERE id = 21;
-- Криминальных организаций в игре нет - раздел правил отдаём лидерам
UPDATE nodes SET title = 'Правила для лидеров и заместителей', icon = 'crown' WHERE id = 34 AND title = 'Правила криминальных организаций';
UPDATE nodes SET description = 'Правительство и Департамент полиции: устав, заявления, жалобы на сотрудников, законы' WHERE id = 56;
UPDATE nodes SET description = 'Помощь с лаунчером, игрой и ошибками мода, восстановление имущества' WHERE id = 20;
